// <auto-generated />
using System;
using Emot.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Emot.Database.Migrations
{
    [DbContext(typeof(EmotDbContext))]
    [Migration("20190329211630_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Emot.Common.Models.Opinion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuthorName");

                    b.Property<int>("OpinionClass");

                    b.Property<int>("OpinionType");

                    b.Property<DateTime?>("Published");

                    b.Property<DateTime>("Scrapped");

                    b.Property<string>("Source");

                    b.Property<int>("Text");

                    b.HasKey("Id");

                    b.ToTable("Opinions");
                });
#pragma warning restore 612, 618
        }
    }
}
